### PR TITLE
Fix for recapture bug and tests failing bug

### LINKED ISSUE #21: reCapture failing on staging and production
Failing on local host too

### LINKED ISSUE #27: You're supposed to run the selenium tests here, but instead you used the default configuration
https://github.com/BSE21-13/FrontEndSite/blob/a8aedb00ef9d40865ba8374714c04f8bfa6721fa/.github/workflows/node.js.yml#L31

@lidik-ops, this test workflow is failing because you're attempting to run ` "test": "react-scripts test",` as defined in package.json.
Possible solutions;
1. In the file .github/workflows/node.js.yml, write the steps to follow inorder to run the selenium tests with python.
2. Update the `test` script in package.json with the right command and remove the `react-scripts test` command

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
closes #21 
closes #27

### CODE REVIEW

File: src/components/Search.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ const Search = ({ hideButtons = false }) => {
 
     if (trimmedInput.length > 2) {
       dispatch(searchActions.sendQuery(trimmedInput));
-
+      console.log('This is the trimmed input', trimmedInput);
```
Comment (123MwanjeMike) [inline src/components/Search.js:25]: Remember to remove this `console.log()` along with the others.

**Review by 123MwanjeMike — COMMENTED** [review]
Looks good to me.
Well done @michael-aries11
